# Generated by Django 5.2.8 on 2025-11-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='berth_preference',
            field=models.CharField(blank=True, choices=[('nothing', 'Nothing'), ('L', 'Lower'), ('M', 'Middle'), ('U', 'Upper')], default='nothing', max_length=10),
        ),
    ]
